---
project_name: gpr25_liver_day30_xdoublets_CD8n_cellcycle
# path to the Cell Ranger ouput; it can even be a CSV file like the one in a Cell Ranger aggregation
input_expression: "/mnt/bioadhoc-temp/Groups/vd-vijay/fcastaneda/rnaseq-sc-standar/gpr25/exp1_day30/raw/cellranger/aggr/gpr25_day30"
# A table of the metadata per library, or the whole metadata ready.
# It can be multiple files: [metadata_lib.csv, demultiplexed_hashtags.rdata]
metadata:
  -  "/home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/gpr25/exp1_day30/results/clustering/gpr25_liver_day30_xdoublets_clean1/.object_meta.data_seurat_mean0.01_pct25_pc15.rds"

# if you don't add "/" at the end, it will append 'project_name'
output_dir: "/mnt/bioadhoc-temp/Groups/vd-vijay/fcastaneda/rnaseq-sc-standar/gpr25/exp1_day30/results/clustering"
filtering:
  subset:
    expr: "nFeature_RNA >= 300 & nFeature_RNA <= 5000 & nCount_RNA >= 200 & nCount_RNA <= 30000 & percent.mt <= 10"
    expre: "doublet_scores <= 0.3"
    expres: "!(orig.HT_ID.global %in% c('Doublet', 'Negative'))"
    express: "orig.extra_meta_donor_e == 'liver'"
    expresss: "RNA_snn_res.0.4 %in% c(0,1,3,4,6)"
  nSamples_expressed: 0.001 # % of cells in which that gene is present
regress_var: [nCount_RNA, percent.mt, cellcycle]
norm: LogNormalize
variable_features:
  #file: ./data/prot_coding_genes.csv
  method: vst
  nfeatures: 2000
  percent: [15, 20, 25]  # iterated
  mean.cutoff: [0.01, 8]
  dispersion.cutoff: [1, Inf]
resolution: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8] # iterated during markers
dim_reduction:
  base: {type: pca, n_comp: 40, chosen_comp: [15,20,25]} # iterated: chosen
  tsne: {perplexity: 'auto', reduction.use: "pca"}
  umap: {n.neighbors: 30, min.dist: 0.3}
markers:
  select: snn_res. # pattern in the metadata's columns
  test: MAST
  avg_logFC: 0.25
  p_val_adj: 0.05
tool: seurat
pipeline: /home/fcastaneda/bin/clustering/
cluster_config: /home/fcastaneda/bin/clustering/cluster.json
environment: clustering
...
